language: csharp
mono: none
dotnet: 3.1.201
solution: DvelopSdk.sln
script:
- dotnet restore
- bash travis/deploy.sh
env:
  global:
  - secure: GAIkqnPDtwIXiq3ai5+svzcqUyBCVwq2eJMt5nsVODjK9w2M6mbgEEPmAdcYsx2Jg5lxzXo9GNkU8tYzyRvjVaJ62km0+K2QeNv9KzgDHCMt7cRNFqe/q9UzGG2frtc2M+j+PiEzD4p/qIpUYzJVWrV8sSrCABRBTIujPwPhnU6owwfDCRiBSowbKhHSxAtGyMzN5Yn52Q7/6YUxaoxjPZPl/5VirQnXRaHqzxCMF2OA9icFqJRP/yiOpUlmYNcAUHc7XsHLxyc0OD6p6hAMEbH4w4AXo9ZYKSdeJDxeJTvh7lLprqI/m63qVjjSHRjkHWs2u0kZPHoD5NIELAil6kIkmdGJaMntGV9wa0+OUrFWtJ/eJKfxvDH6YliEy84FtOjPJ193tCqGTNnHic5E3HclLxsr39OFKwD2dDZRorZwg4HWDJhBFNW5zUyi7K3HHlQTdRMYFVZLeSAEEAOt7xAze4CJpvq+WrXLKbDmKvNXzWUbyBfiXoA9VZ+4seDn5Ir3CqJQW5xVcU0h/w/vrmG7x6rr3J/aFQ0yp18KaX126wgSeQFitHlmpjK05TQPUFUa+6GfidYVuir7woDUad5j0YEuwt7OjtkKOkgLIVc7qOmoyRpaveySlf4Y0qb6lFHm/M0TY51O51TvOKD3VZ4M2pIarXhYNwMwSx7VgWU=
